version: '3.8'
services:
  postgres:
    image: postgres:14
    restart: always
    ports:
      - 5432:5432
    networks:
      - app
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test-task
    
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    networks:
      - app
    environment:
      - REDIS_REPLICATION_MODE=master
    command: ['redis-server', '--bind', 'redis', '--port', '6379']

networks:
  app:
    name: test-network
